# Copyright (c) 2026 eele14. All Rights Reserved.
services:
  app:
    build: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calc.rule=Host(`terriblecode.eele14.dev`)"
      - "traefik.http.routers.calc.entrypoints=web,websecure"
      - "traefik.http.services.calc.loadbalancer.server.port=${PORT}"

networks:
  dokploy-network:
    external: true
