# Copyright (c) 2026 eele14. All Rights Reserved.
services:
  app:
    build: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
